name = "FemtoPhysics-Registry"
uuid = "6204b28a-60fd-11ed-1861-1118b0e812d7"
repo = "https://github.com/FemtoPhysics/FemtoPhysics-Registry.git"
description = "A small `julia` registry repo for `FemtoPhysics`."

[packages]
4031b2b4-dfe3-49e7-a2f4-bdce617a3083 = { name = "FemtoSpectra", path = "FemtoSpectra" }
9d743a50-9615-44c3-a48c-d0a59e57ed8d = { name = "ImgAnalysis", path = "ImgAnalysis" }
